# Configuración básica de Jekyll
title: Arigsa - Portfolio
description: >-
  Portfolio personal de Arigsa, investigador y doctorando en
  Ingeniería y Producción Industrial.
baseurl: "/portfolio-website" # el nombre de tu repositorio GitHub
url: "https://arigsae.github.io" # tu nombre de usuario GitHub

# Configuración de construcción
exclude:
  - .git/
  - .github/
  - src/
  - node_modules/
  - README.md
  - package.json
  - package-lock.json

# Configuración de tema
theme: jekyll-theme-minimal

# Especificar directamente los archivos a incluir
include:
  - "public/**/*"
  - "*.html"
  - "src/**/*.js"

# Deshabilitar procesamiento SCSS
sass:
  style: expanded
